## Recomendador de Músicas

In [1]:
import pandas as pd
import numpy as np

In [2]:
dados = pd.read_csv('Dados/Dados_totais.csv')
dados_generos = pd.read_csv('Dados/data_by_genres.csv')
dados_anos = pd.read_csv('Dados/data_by_year.csv')

In [3]:
dados.head()

valence  year  acousticness       artists  danceability  duration_ms  \
0    0.285  2000       0.00239      Coldplay         0.429       266773   
1    0.613  2000       0.14300       OutKast         0.843       270507   
2    0.400  2000       0.00958   Linkin Park         0.556       216880   
3    0.543  2000       0.00664  3 Doors Down         0.545       233933   
4    0.760  2000       0.03020        Eminem         0.949       284200   

   energy  explicit                      id  instrumentalness  key  liveness  \
0   0.661         0  3AJwUDP919kvQ9QcozQPxg          0.000121   11    0.2340   
1   0.806         1  0I3q5fE6wg7LIfHGngUTnV          0.000000    4    0.0771   
2   0.864         0  60a0Rd6pjrkxjPbaKzXjfq          0.000000    3    0.2090   
3   0.865         0  6ZOBP3NvffbU4SZcrnt1k6          0.000011   11    0.1680   
4   0.661         1  3yfqSUWxFvZELEM4PmlwIR          0.000000    5    0.0454   

   loudness  mode                 name  popularity  speechiness    tempo  \
0    -7.227     1               Yellow          84       0.0281  173.372   
1    -5.946     0          Ms. Jackson          80       0.2690   94.948   
2    -5.870     0           In the End          84       0.0584  105.143   
3    -5.708     0           Kryptonite          78       0.0286   99.009   
4    -4.244     0  The Real Slim Shady          80       0.0572  104.504   

                   artists_song  
0             Coldplay - Yellow  
1         OutKast - Ms. Jackson  
2      Linkin Park - In the End  
3     3 Doors Down - Kryptonite  
4  Eminem - The Real Slim Shady

In [4]:
dados['year'].unique()

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020],
      dtype=int64)

In [5]:
dados.shape

(20311, 19)

In [6]:
dados.drop(['explicit', 'key', 'mode'], axis=1)
dados.head(2)

valence  year  acousticness   artists  danceability  duration_ms  energy  \
0    0.285  2000       0.00239  Coldplay         0.429       266773   0.661   
1    0.613  2000       0.14300   OutKast         0.843       270507   0.806   

   explicit                      id  instrumentalness  key  liveness  \
0         0  3AJwUDP919kvQ9QcozQPxg          0.000121   11    0.2340   
1         1  0I3q5fE6wg7LIfHGngUTnV          0.000000    4    0.0771   

   loudness  mode         name  popularity  speechiness    tempo  \
0    -7.227     1       Yellow          84       0.0281  173.372   
1    -5.946     0  Ms. Jackson          80       0.2690   94.948   

            artists_song  
0      Coldplay - Yellow  
1  OutKast - Ms. Jackson

In [7]:
# Verificação de dados nulos
dados.isnull().sum()

valence             0
year                0
acousticness        0
artists             0
danceability        0
duration_ms         0
energy              0
explicit            0
id                  0
instrumentalness    0
key                 0
liveness            0
loudness            0
mode                0
name                0
popularity          0
speechiness         0
tempo               0
artists_song        0
dtype: int64

In [8]:
# Verificando a presença de dados do tipo NaN
dados.isna().sum()

valence             0
year                0
acousticness        0
artists             0
danceability        0
duration_ms         0
energy              0
explicit            0
id                  0
instrumentalness    0
key                 0
liveness            0
loudness            0
mode                0
name                0
popularity          0
speechiness         0
tempo               0
artists_song        0
dtype: int64

In [9]:
dados_generos.head(2)

mode                  genres  acousticness  danceability   duration_ms  \
0     1  21st century classical      0.979333      0.162883  1.602977e+05   
1     1                   432hz      0.494780      0.299333  1.048887e+06   

     energy  instrumentalness  liveness   loudness  speechiness       tempo  \
0  0.071317          0.606834    0.3616 -31.514333     0.040567   75.336500   
1  0.450678          0.477762    0.1310 -16.854000     0.076817  120.285667   

    valence  popularity  key  
0  0.103783   27.833333    6  
1  0.221750   52.500000    5

In [10]:
dados_generos = dados_generos.drop(['key', 'mode'], axis=1)
dados_generos.head(2)

genres  acousticness  danceability   duration_ms    energy  \
0  21st century classical      0.979333      0.162883  1.602977e+05  0.071317   
1                   432hz      0.494780      0.299333  1.048887e+06  0.450678   

   instrumentalness  liveness   loudness  speechiness       tempo   valence  \
0          0.606834    0.3616 -31.514333     0.040567   75.336500  0.103783   
1          0.477762    0.1310 -16.854000     0.076817  120.285667  0.221750   

   popularity  
0   27.833333  
1   52.500000

In [11]:
# Verificando a presença de dados Nulos
dados.isnull().sum()

valence             0
year                0
acousticness        0
artists             0
danceability        0
duration_ms         0
energy              0
explicit            0
id                  0
instrumentalness    0
key                 0
liveness            0
loudness            0
mode                0
name                0
popularity          0
speechiness         0
tempo               0
artists_song        0
dtype: int64

In [12]:
# Verificando a presença de dados do tipo NaN
dados.isna().sum()

valence             0
year                0
acousticness        0
artists             0
danceability        0
duration_ms         0
energy              0
explicit            0
id                  0
instrumentalness    0
key                 0
liveness            0
loudness            0
mode                0
name                0
popularity          0
speechiness         0
tempo               0
artists_song        0
dtype: int64

In [13]:
dados_anos.head(2)

mode  year  acousticness  danceability    duration_ms    energy  \
0     1  1921      0.886896      0.418597  260537.166667  0.231815   
1     1  1922      0.938592      0.482042  165469.746479  0.237815   

   instrumentalness  liveness   loudness  speechiness       tempo   valence  \
0          0.344878   0.20571 -17.048667     0.073662  101.531493  0.379327   
1          0.434195   0.24072 -19.275282     0.116655  100.884521  0.535549   

   popularity  key  
0    0.653333    2  
1    0.140845   10

In [14]:
dados_anos['year'].unique()

array([1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931,
       1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942,
       1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953,
       1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964,
       1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975,
       1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986,
       1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997,
       1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008,
       2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019,
       2020], dtype=int64)

In [15]:
# Filtrar os dados a partir dos anos 2000
dados_anos = dados_anos[dados_anos['year'] >= 2000]
dados_anos['year'].unique()

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020],
      dtype=int64)

In [16]:
dados_anos = dados_anos.drop(['key', 'mode'], axis=1)
dados_anos.head(2)

year  acousticness  danceability    duration_ms    energy  \
79  2000      0.289323      0.590918  242724.642638  0.625413   
80  2001      0.286842      0.583318  240307.796010  0.626986   

    instrumentalness  liveness  loudness  speechiness       tempo   valence  \
79          0.101168  0.197686 -8.247766     0.089205  118.999323  0.559475   
80          0.107214  0.187026 -8.305095     0.089182  117.765399  0.541479   

    popularity  
79   46.684049  
80   48.750125

In [17]:
# Ressetando o index
dados_anos.reset_index().head(5)

index  year  acousticness  danceability    duration_ms    energy  \
0     79  2000      0.289323      0.590918  242724.642638  0.625413   
1     80  2001      0.286842      0.583318  240307.796010  0.626986   
2     81  2002      0.282624      0.576160  239503.283000  0.641270   
3     82  2003      0.256471      0.575763  244670.575230  0.660165   
4     83  2004      0.280559      0.567680  237378.708037  0.648868   

   instrumentalness  liveness  loudness  speechiness       tempo   valence  \
0          0.101168  0.197686 -8.247766     0.089205  118.999323  0.559475   
1          0.107214  0.187026 -8.305095     0.089182  117.765399  0.541479   
2          0.088048  0.193911 -7.686640     0.084308  119.239738  0.542397   
3          0.083049  0.196976 -7.485545     0.093926  120.914622  0.530504   
4          0.077934  0.202199 -7.601655     0.094239  121.290346  0.524489   

   popularity  
0   46.684049  
1   48.750125  
2   48.655500  
3   48.626407  
4   49.273143

In [18]:
dados_anos.isnull().sum()

year                0
acousticness        0
danceability        0
duration_ms         0
energy              0
instrumentalness    0
liveness            0
loudness            0
speechiness         0
tempo               0
valence             0
popularity          0
dtype: int64

In [19]:
dados_anos.isna().sum()

year                0
acousticness        0
danceability        0
duration_ms         0
energy              0
instrumentalness    0
liveness            0
loudness            0
speechiness         0
tempo               0
valence             0
popularity          0
dtype: int64

## 1.5 Análise Gráfica

In [20]:
import plotly.express as px

In [21]:
fig = px.line(dados_anos, x='year', y='loudness', markers=True, title='Variação do loudness conforme os anos')
fig.show()

In [22]:
import plotly.graph_objects as go

In [23]:
fig = go.Figure()

fig.add_trace(go.Scatter(x=dados_anos['year'], y=dados_anos['acousticness'], name='Acousticness'))
fig.add_trace(go.Scatter(x=dados_anos['year'], y=dados_anos['valence'], name='Valence'))
fig.add_trace(go.Scatter(x=dados_anos['year'], y=dados_anos['energy'], name='Energy'))
fig.add_trace(go.Scatter(x=dados_anos['year'], y=dados_anos['instrumentalness'], name='Instrumentalness'))
fig.add_trace(go.Scatter(x=dados_anos['year'], y=dados_anos['liveness'], name='Liveness'))
fig.add_trace(go.Scatter(x=dados_anos['year'], y=dados_anos['speechiness'], name='Speechiness'))
fig.show()

In [24]:
# Verificando a correação entre as variáveis

fig = px.imshow(dados.corr(), text_auto=True)
fig.show()

C:\Users\Fabiano\AppData\Local\Temp\ipykernel_11768\366216162.py:3: FutureWarning:

The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.



# Clusterização por gênero

## PCA e StandardScaler

In [25]:
dados_generos

genres  acousticness  danceability   duration_ms  \
0     21st century classical      0.979333      0.162883  1.602977e+05   
1                      432hz      0.494780      0.299333  1.048887e+06   
2                      8-bit      0.762000      0.712000  1.151770e+05   
3                         []      0.651417      0.529093  2.328809e+05   
4                 a cappella      0.676557      0.538961  1.906285e+05   
...                      ...           ...           ...           ...   
2968                    zolo      0.222625      0.547082  2.580991e+05   
2969                 zouglou      0.161000      0.863000  2.063200e+05   
2970                    zouk      0.263261      0.748889  3.060728e+05   
2971            zurich indie      0.993000      0.705667  1.984173e+05   
2972                  zydeco      0.421038      0.629409  1.716717e+05   

        energy  instrumentalness  liveness   loudness  speechiness  \
0     0.071317          0.606834  0.361600 -31.514333     0.040567   
1     0.450678          0.477762  0.131000 -16.854000     0.076817   
2     0.818000          0.876000  0.126000  -9.180000     0.047000   
3     0.419146          0.205309  0.218696 -12.288965     0.107872   
4     0.316434          0.003003  0.172254 -12.479387     0.082851   
...        ...               ...       ...        ...          ...   
2968  0.610240          0.143872  0.204206 -11.295878     0.061088   
2969  0.909000          0.000000  0.108000  -5.985000     0.081300   
2970  0.622444          0.257227  0.089678 -10.289222     0.038778   
2971  0.172667          0.468633  0.179667 -11.453333     0.348667   
2972  0.609369          0.019248  0.255877  -9.854825     0.050491   

           tempo   valence  popularity  
0      75.336500  0.103783   27.833333  
1     120.285667  0.221750   52.500000  
2     133.444000  0.975000   48.000000  
3     112.857352  0.513604   20.859882  
4     112.110362  0.448249   45.820071  
...          ...       ...         ...  
2968  125.494919  0.596155   33.778943  
2969  119.038000  0.845000   58.000000  
2970  101.965222  0.824111   46.666667  
2971   91.278000  0.739000    0.000000  
2972  126.366087  0.808544   30.261905  

[2973 rows x 12 columns]

In [26]:
# Verificando se cada linha é um gênero

dados_generos['genres'].value_counts().sum()

# Dado que cada linha possui um valor único, não é possível realizar alguma análise, em complemento,
# os algoritmos de clusterização trabalham apenas com valores numéricos uma solução possível é dumificar
# as variáveis, no entando, isso seria um problema pois aumentaria a dimensionalidade dos dados em 2973 colunas,
# portanto a solução neste momento é a exclusão desta coluna.  

2973

In [27]:
dados_generos1 = dados_generos.drop('genres', axis=1)
dados_generos1

acousticness  danceability   duration_ms    energy  instrumentalness  \
0         0.979333      0.162883  1.602977e+05  0.071317          0.606834   
1         0.494780      0.299333  1.048887e+06  0.450678          0.477762   
2         0.762000      0.712000  1.151770e+05  0.818000          0.876000   
3         0.651417      0.529093  2.328809e+05  0.419146          0.205309   
4         0.676557      0.538961  1.906285e+05  0.316434          0.003003   
...            ...           ...           ...       ...               ...   
2968      0.222625      0.547082  2.580991e+05  0.610240          0.143872   
2969      0.161000      0.863000  2.063200e+05  0.909000          0.000000   
2970      0.263261      0.748889  3.060728e+05  0.622444          0.257227   
2971      0.993000      0.705667  1.984173e+05  0.172667          0.468633   
2972      0.421038      0.629409  1.716717e+05  0.609369          0.019248   

      liveness   loudness  speechiness       tempo   valence  popularity  
0     0.361600 -31.514333     0.040567   75.336500  0.103783   27.833333  
1     0.131000 -16.854000     0.076817  120.285667  0.221750   52.500000  
2     0.126000  -9.180000     0.047000  133.444000  0.975000   48.000000  
3     0.218696 -12.288965     0.107872  112.857352  0.513604   20.859882  
4     0.172254 -12.479387     0.082851  112.110362  0.448249   45.820071  
...        ...        ...          ...         ...       ...         ...  
2968  0.204206 -11.295878     0.061088  125.494919  0.596155   33.778943  
2969  0.108000  -5.985000     0.081300  119.038000  0.845000   58.000000  
2970  0.089678 -10.289222     0.038778  101.965222  0.824111   46.666667  
2971  0.179667 -11.453333     0.348667   91.278000  0.739000    0.000000  
2972  0.255877  -9.854825     0.050491  126.366087  0.808544   30.261905  

[2973 rows x 11 columns]

In [28]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [29]:
SEED = 1224
np.random.seed(SEED)

pca_pipeline = Pipeline([('scaler', StandardScaler()), ('PCA', PCA(n_components=2, random_state=SEED))])

In [30]:
genre_embedding_pca = pca_pipeline.fit_transform(dados_generos1)
projection = pd.DataFrame(columns=['x', 'y'], data=genre_embedding_pca)

In [31]:
projection

x         y
0     5.910268 -0.011146
1     2.787093  4.498483
2    -0.757538 -1.258495
3     1.020521 -0.931690
4     0.753911 -0.999861
...        ...       ...
2968 -0.475136 -0.017126
2969 -3.026756 -1.304983
2970 -0.832511 -1.089726
2971  1.774790 -3.695233
2972 -1.028069 -1.390709

[2973 rows x 2 columns]

# Classificando os dados com o K-MEANS

In [32]:
from sklearn.cluster import KMeans

In [33]:
# Parâmetro Verbose=True nos trás as interações que estão ocorrendo no modelo
kmeans_pca = KMeans(n_clusters=5, verbose=True, random_state=SEED)

kmeans_pca.fit(projection)

dados_generos['cluster_pca'] = kmeans_pca.predict(projection)
projection['cluster_pca'] = kmeans_pca.predict(projection)

Initialization complete
Iteration 0, inertia 4523.567815543701.
Iteration 1, inertia 3668.985552156032.
Iteration 2, inertia 3624.730925711825.
Iteration 3, inertia 3602.495813758821.
Iteration 4, inertia 3588.060791240496.
Iteration 5, inertia 3575.439570259312.
Iteration 6, inertia 3566.376131163027.
Iteration 7, inertia 3562.5917284575003.
Iteration 8, inertia 3560.3144677009413.
Iteration 9, inertia 3558.885495152658.
Iteration 10, inertia 3558.002748934059.
Iteration 11, inertia 3557.7295547754984.
Converged at iteration 11: center shift 9.319981044864924e-05 within tolerance 0.0002709886847099652.
Initialization complete
Iteration 0, inertia 3650.5166847646597.
Iteration 1, inertia 3552.8915365648218.
Iteration 2, inertia 3528.942542123229.
Iteration 3, inertia 3518.849132048718.
Iteration 4, inertia 3512.671791613983.
Iteration 5, inertia 3509.174107824749.
Iteration 6, inertia 3506.388333551382.
Iteration 7, inertia 3505.0910743094155.
Iteration 8, inertia 3504.6465117385005.
C

In [34]:
projection

x         y  cluster_pca
0     5.910268 -0.011146            3
1     2.787093  4.498483            3
2    -0.757538 -1.258495            4
3     1.020521 -0.931690            1
4     0.753911 -0.999861            1
...        ...       ...          ...
2968 -0.475136 -0.017126            2
2969 -3.026756 -1.304983            4
2970 -0.832511 -1.089726            4
2971  1.774790 -3.695233            1
2972 -1.028069 -1.390709            4

[2973 rows x 3 columns]

In [35]:
projection['generos'] = dados_generos['genres']

In [36]:
projection

x         y  cluster_pca                 generos
0     5.910268 -0.011146            3  21st century classical
1     2.787093  4.498483            3                   432hz
2    -0.757538 -1.258495            4                   8-bit
3     1.020521 -0.931690            1                      []
4     0.753911 -0.999861            1              a cappella
...        ...       ...          ...                     ...
2968 -0.475136 -0.017126            2                    zolo
2969 -3.026756 -1.304983            4                 zouglou
2970 -0.832511 -1.089726            4                    zouk
2971  1.774790 -3.695233            1            zurich indie
2972 -1.028069 -1.390709            4                  zydeco

[2973 rows x 4 columns]

In [37]:
fig = px.scatter(
    projection, x='x', y='y', color='cluster_pca', hover_data = ['x', 'y', 'generos'])
fig.show()

In [38]:
# Passaos a posição [1] já que a posição [0] é do StandardScaler e a posição [1] é do PCA
# output - 1ª posição - poder de explicação do 'x': 0,34
# output - 2ª posição - poder de explicação do 'y': 0,14
pca_pipeline[1].explained_variance_ratio_

array([0.34986105, 0.14284565])

In [39]:
# capacidade explicativa do modelo
pca_pipeline[1].explained_variance_ratio_.sum()

0.49270669947266393

In [40]:
# Removendo o 'ratio' do fim da linha de comando temos abaixo quantas variáveis estão sendo explicadas
# pelo modelo
pca_pipeline[1].explained_variance_

array([3.84976644, 1.57183087])

In [41]:
# Temos que o modelo explica 5,4 variaveis
pca_pipeline[1].explained_variance_.sum()

5.421597305805696

# Clusterização por música

## Redução de dimensionalidade com PCA

In [42]:
dados.head()

valence  year  acousticness       artists  danceability  duration_ms  \
0    0.285  2000       0.00239      Coldplay         0.429       266773   
1    0.613  2000       0.14300       OutKast         0.843       270507   
2    0.400  2000       0.00958   Linkin Park         0.556       216880   
3    0.543  2000       0.00664  3 Doors Down         0.545       233933   
4    0.760  2000       0.03020        Eminem         0.949       284200   

   energy  explicit                      id  instrumentalness  key  liveness  \
0   0.661         0  3AJwUDP919kvQ9QcozQPxg          0.000121   11    0.2340   
1   0.806         1  0I3q5fE6wg7LIfHGngUTnV          0.000000    4    0.0771   
2   0.864         0  60a0Rd6pjrkxjPbaKzXjfq          0.000000    3    0.2090   
3   0.865         0  6ZOBP3NvffbU4SZcrnt1k6          0.000011   11    0.1680   
4   0.661         1  3yfqSUWxFvZELEM4PmlwIR          0.000000    5    0.0454   

   loudness  mode                 name  popularity  speechiness    tempo  \
0    -7.227     1               Yellow          84       0.0281  173.372   
1    -5.946     0          Ms. Jackson          80       0.2690   94.948   
2    -5.870     0           In the End          84       0.0584  105.143   
3    -5.708     0           Kryptonite          78       0.0286   99.009   
4    -4.244     0  The Real Slim Shady          80       0.0572  104.504   

                   artists_song  
0             Coldplay - Yellow  
1         OutKast - Ms. Jackson  
2      Linkin Park - In the End  
3     3 Doors Down - Kryptonite  
4  Eminem - The Real Slim Shady

In [43]:
# Verifica-se que temos 875 artistas diferentes
dados['artists'].value_counts()

Drake                   170
Taylor Swift            156
Eminem                  147
Kanye West              136
BTS                     122
                       ... 
Of Monsters and Men       7
The Living Tombstone      7
Clean Bandit              7
Nelly Furtado             6
Empire of the Sun         6
Name: artists, Length: 875, dtype: int64

In [44]:
# Verifica-se aqui que temos 20311 valores únicos
dados['artists_song'].value_counts()

Coldplay - Yellow                                                   1
Juice WRLD - Intro                                                  1
Carrie Underwood - The Champion - Bonus Track                       1
YoungBoy Never Broke Again - Cross Me (feat. Lil Baby and Plies)    1
Twenty One Pilots - Morph                                           1
                                                                   ..
Taylor Swift - Come Back...Be Here                                  1
Banda El Recodo - Me Gusta Todo De Ti                               1
Michael Bublé - The Christmas Song                                  1
Glee Cast - Smooth Criminal (Glee Cast Version) (feat. 2CELLOS)     1
Eminem - Darkness                                                   1
Name: artists_song, Length: 20311, dtype: int64

In [45]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(dtype=int)
colunas_ohe = ohe.fit_transform(dados[['artists']]).toarray()
dados2 = dados.drop('artists', axis=1)

dados_musicais_dummies = pd.concat([dados2, pd.DataFrame(colunas_ohe, columns=ohe.get_feature_names_out(['artists']))], axis=1)
dados_musicais_dummies

valence  year  acousticness  danceability  duration_ms  energy  \
0        0.285  2000       0.00239         0.429       266773   0.661   
1        0.613  2000       0.14300         0.843       270507   0.806   
2        0.400  2000       0.00958         0.556       216880   0.864   
3        0.543  2000       0.00664         0.545       233933   0.865   
4        0.760  2000       0.03020         0.949       284200   0.661   
...        ...   ...           ...           ...          ...     ...   
20306    0.187  2020       0.57400         0.445       176250   0.330   
20307    0.240  2020       0.81500         0.467       179188   0.429   
20308    0.466  2020       0.31000         0.562       253613   0.686   
20309    0.522  2020       0.20400         0.598       230600   0.472   
20310    0.195  2020       0.00998         0.671       337147   0.623   

       explicit                      id  instrumentalness  key  ...  \
0             0  3AJwUDP919kvQ9QcozQPxg          0.000121   11  ...   
1             1  0I3q5fE6wg7LIfHGngUTnV          0.000000    4  ...   
2             0  60a0Rd6pjrkxjPbaKzXjfq          0.000000    3  ...   
3             0  6ZOBP3NvffbU4SZcrnt1k6          0.000011   11  ...   
4             1  3yfqSUWxFvZELEM4PmlwIR          0.000000    5  ...   
...         ...                     ...               ...  ...  ...   
20306         0  0PUkanqCGTb6qseXPKOw1F          0.000000    9  ...   
20307         0  6Iw6fQVKZi0fWtEQBrTFcP          0.000052    6  ...   
20308         0  308prODCCD0O660tIktbUi          0.022500    7  ...   
20309         1  2f8y4CuG57UJEmkG3ujd0D          0.000015    0  ...   
20310         1  5SiZJoLXp3WOl3J4C8IK0d          0.000008    2  ...   

       artists_Zara Larsson  artists_Zedd  artists_alt-J artists_blackbear  \
0                         0             0              0                 0   
1                         0             0              0                 0   
2                         0             0              0                 0   
3                         0             0              0                 0   
4                         0             0              0                 0   
...                     ...           ...            ...               ...   
20306                     0             0              0                 0   
20307                     0             0              0                 0   
20308                     0             0              0                 0   
20309                     0             0              0                 0   
20310                     0             0              0                 0   

       artists_blink-182  artists_deadmau5  artists_for KING & COUNTRY  \
0                      0                 0                           0   
1                      0                 0                           0   
2                      0                 0                           0   
3                      0                 0                           0   
4                      0                 0                           0   
...                  ...               ...                         ...   
20306                  0                 0                           0   
20307                  0                 0                           0   
20308                  0                 0                           0   
20309                  0                 0                           0   
20310                  0                 0                           0   

      artists_fun.  artists_girl in red  artists_iann dior  
0                0                    0                  0  
1                0                    0                  0  
2                0                    0                  0  
3                0                    0                  0  
4                0                    0                  0  
...            ...                  ...                ...  
20306            0      

In [46]:
dados.shape

(20311, 19)

In [47]:
dados_musicais_dummies.shape

(20311, 893)

In [49]:
# passando o n_components=0.7 determinamos que espera-se uma taxa de aprendizado de 70%

pca_pipeline = Pipeline([('scaler', StandardScaler()), ('PCA', PCA(n_components=0.7, random_state=SEED))])

# Aplicando o drop para apagar as variáveis de string
music_embedding_pca = pca_pipeline.fit_transform(dados_musicais_dummies.drop(['id', 'name', 'artists_song'], axis=1))
projection_m = pd.DataFrame(data=music_embedding_pca)

In [50]:
# Verifica-se que com uma taxa de aprendizado de 70% são necessárias 613 componentes ou colunas
pca_pipeline[1].n_components_

613

## Aplicação do cluster K-Means

In [51]:
kmeans_pca_pipeline = KMeans(n_clusters=50, verbose=False, random_state=SEED)

kmeans_pca_pipeline.fit(projection_m)

dados['cluster_pca'] = kmeans_pca_pipeline.predict(projection_m)
projection_m['cluster_pca'] = kmeans_pca_pipeline.predict(projection_m)

In [52]:
projection_m['artist'] = dados['artists']
projection_m['song'] = dados['artists_song']

In [53]:
projection_m

0         1         2         3         4         5         6  \
0      0.378041 -1.105670 -0.217875  2.141618  0.460543  0.389330  0.357378   
1     -1.835784  0.968268  1.957886 -2.040361  0.482239  1.226603 -0.639418   
2     -0.812090 -0.923825  0.059168  0.972975 -0.437157  1.290976  1.071816   
3     -0.784928 -1.590062 -0.058206  0.553700 -0.130400  1.856148  1.122687   
4     -2.168298  1.079448  1.225286 -1.395836  1.274807  1.751917 -0.630658   
...         ...       ...       ...       ...       ...       ...       ...   
20306  1.289224  2.028642 -2.338149  1.247367 -0.116317 -0.627552  0.802632   
20307  1.042660  2.314540 -0.653191  1.170746 -0.751908 -0.329202  1.950838   
20308  0.885203  0.564691 -1.443982  0.850840  1.037138 -0.350518  0.556076   
20309 -0.525831  3.565280  0.121437 -0.421865 -0.276961 -1.435964 -2.718264   
20310 -1.495765  2.396163  2.955234  0.450812  1.751338 -0.518806 -0.077228   

              7         8         9  ...       606       607       608  \
0     -0.829060 -1.064067 -2.822201  ... -0.007201  0.009958 -0.013029   
1     -1.116720  0.601654 -1.535073  ...  0.007943  0.021621 -0.035924   
2      0.449164  1.948167 -1.273368  ... -0.004488 -0.002567 -0.002016   
3     -1.812624  0.509192 -1.145719  ... -0.071470  0.019352  0.040598   
4     -0.029179  0.417433 -2.159679  ... -0.005433  0.006327 -0.009567   
...         ...       ...       ...  ...       ...       ...       ...   
20306 -0.513150  0.230640 -0.392388  ... -0.182005  0.313566  0.285628   
20307 -1.064144 -1.913865  0.243745  ... -0.280132  0.273006  0.064507   
20308 -0.836172  0.557241  0.549961  ...  0.265335  0.049588  0.317182   
20309  0.620472 -0.033559  0.178014  ... -0.699305  0.597014 -0.524919   
20310  2.360976  0.879305 -1.306589  ... -0.005364  0.006604 -0.009449   

            609       610       611           612  cluster_pca         artist  \
0     -0.003145  0.015032 -0.038177  2.180804e-12            1       Coldplay   
1     -0.023443  0.001881 -0.031168  5.650501e-12            5        OutKast   
2     -0.014941  0.002420 -0.012432  2.095571e-12            1    Linkin Park   
3     -0.160847  0.016884 -0.056636  2.013741e-12            1   3 Doors Down   
4      0.007437  0.013157 -0.014763  1.354849e-12            5         Eminem   
...         ...       ...       ...           ...          ...            ...   
20306  0.092385 -0.074066 -0.167317 -2.109073e-11            5          Bazzi   
20307  0.016715 -0.038420  0.010711 -3.663712e-12            5  Bryson Tiller   
20308  0.028761 -0.264281 -0.016075 -3.952760e-11           21    Fleet Foxes   
20309  0.248584  0.063315  0.159979 -6.457016e-11            5          Gunna   
20310  0.007214  0.013135 -0.015156  1.367882e-12            5         Eminem   

                                     song  
0                       Coldplay - Yellow  
1                   OutKast - Ms. Jackson  
2                Linkin Park - In the End  
3               3 Doors Down - Kryptonite  
4            Eminem - The Real Slim Shady  
...                                   ...  
20306      Bazzi - I Don't Think I'm Okay  
20307  Bryson Tiller - Timeless Interlude  
20308              Fleet Foxes - Sunblind  
20309      Gunna - NASTY GIRL / ON CAMERA  
20310                   Eminem - Darkness  

[20311 rows x 616 columns]

In [54]:
# No pca, as colunas são ordenadas pelo seu poder de explicação começando na 0 e assim sucessivamente.
# Portando, para o gráfico será selecionado as colunas 0 e 1 para plotar o gráfico pois são as que melhor
# explicam o fenômeno.

fig = px.scatter(
    projection_m, x = 0, y=1, color='cluster_pca', hover_data = [0, 1, 'song'])
fig.show()

In [55]:
# Verificando se o poder de explicação da cluster está em 70%
pca_pipeline[1].explained_variance_ratio_.sum()

0.7003652785775395

In [56]:
# Para ver o poder de explicação de cada coluna usamos:
pca_pipeline[1].explained_variance_ratio_

array([0.00445349, 0.00314392, 0.00235311, 0.00224424, 0.00165394,
       0.00163249, 0.00149837, 0.00147503, 0.00142022, 0.00135103,
       0.0013271 , 0.00129905, 0.00125901, 0.00123213, 0.00116433,
       0.00113277, 0.00113199, 0.00113141, 0.00113076, 0.00113005,
       0.00112993, 0.00112896, 0.00112881, 0.00112873, 0.0011287 ,
       0.00112858, 0.00112852, 0.00112844, 0.00112842, 0.00112803,
       0.00112794, 0.00112788, 0.0011278 , 0.0011276 , 0.00112757,
       0.00112749, 0.00112747, 0.00112744, 0.00112743, 0.00112739,
       0.00112737, 0.00112734, 0.00112732, 0.00112727, 0.0011272 ,
       0.00112713, 0.0011271 , 0.00112708, 0.00112706, 0.00112702,
       0.00112701, 0.00112699, 0.00112698, 0.00112694, 0.00112689,
       0.00112684, 0.0011268 , 0.0011268 , 0.00112678, 0.00112674,
       0.00112673, 0.00112671, 0.00112669, 0.00112668, 0.00112666,
       0.00112663, 0.0011266 , 0.00112659, 0.00112658, 0.00112657,
       0.00112656, 0.00112654, 0.00112652, 0.00112651, 0.00112

In [57]:
# das 613 colunas iniciais o modelo consegue explicar 623 componentes
pca_pipeline[1].explained_variance_.sum()

623.3557884853608

In [58]:
pca_pipeline[1].explained_variance_

array([3.96380357, 2.79822238, 2.09436732, 1.99747182, 1.47208029,
       1.45298794, 1.33361775, 1.31283893, 1.26405904, 1.20247438,
       1.18117554, 1.15621143, 1.1205713 , 1.09665106, 1.03630414,
       1.00821457, 1.00752309, 1.00700473, 1.00642353, 1.00579744,
       1.00568505, 1.00482269, 1.00469096, 1.00461753, 1.00459477,
       1.00448481, 1.004435  , 1.00436413, 1.00434579, 1.00399793,
       1.00391797, 1.00386147, 1.00379104, 1.00361364, 1.00358228,
       1.00351435, 1.00349591, 1.00347418, 1.00345863, 1.00342458,
       1.0034128 , 1.00338036, 1.00336187, 1.00332128, 1.00325541,
       1.00319903, 1.00317191, 1.00315142, 1.00313149, 1.00309703,
       1.00308848, 1.00307446, 1.00306229, 1.00302653, 1.00298338,
       1.00293653, 1.00290471, 1.002901  , 1.00288633, 1.00284824,
       1.00284017, 1.0028224 , 1.00280475, 1.00279236, 1.00277246,
       1.00274936, 1.00272093, 1.0027157 , 1.00270822, 1.00269704,
       1.0026856 , 1.00267054, 1.00265359, 1.00264645, 1.00263